######################################################################
##
## Filename: cpu55.udo
## Created on: Sat Jan 25 16:11:19 中国标准时间 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
