######################################################################
##
## Filename: cpu_tb.udo
## Created on: Thu Oct 31 10:11:22 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
