######################################################################
##
## Filename: cpu_with_cp0_tb.udo
## Created on: Sun Mar 09 12:44:14 中国标准时间 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
