######################################################################
##
## Filename: datamen_tb.udo
## Created on: Tue Oct 29 15:32:31 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
