######################################################################
##
## Filename: div_tb.udo
## Created on: Mon Apr 14 18:10:32 中国标准时间 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
