######################################################################
##
## Filename: file_write.udo
## Created on: Thu Oct 31 12:46:04 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
