######################################################################
##
## Filename: iram_tb.udo
## Created on: Sat Apr 12 22:14:25 中国标准时间 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
