######################################################################
##
## Filename: mux32x32_tb.udo
## Created on: Sat Oct 12 20:06:25 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
