######################################################################
##
## Filename: myreg_tb.udo
## Created on: Sat Oct 12 19:08:28 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
