######################################################################
##
## Filename: pipe_id.udo
## Created on: Sun Mar 09 15:10:46 中国标准时间 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
